services:
  postgres:
    image: postgres:16-alpine
    container_name: banking-lab-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: banking
      POSTGRES_USER: banking
      POSTGRES_PASSWORD: banking
    ports:
      - "5432:5432"
    volumes:
      - banking-pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U banking -d banking"]
      interval: 5s
      timeout: 3s
      retries: 20

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: banking-lab-pgadmin
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@banking.local
      PGADMIN_DEFAULT_PASSWORD: banking
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    profiles: ["tools"]

volumes:
  banking-pg-data:
